# Generated by Django 3.2.23 on 2024-01-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contract_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sub_contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contacts.subcontractor'),
        ),
    ]
