# Generated by Django 3.2.23 on 2024-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_sub_contrator_project_sub_contractor'),
        ('contacts', '0004_auto_20240119_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='project',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
