# Generated by Django 3.2.23 on 2024-01-25 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Username must not be less than three')])),
                ('email', models.EmailField(help_text="User's Email", max_length=254)),
                ('password', models.CharField(help_text="User's password", max_length=50, validators=[django.core.validators.MinLengthValidator(6, 'Password should not be less than six characters')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
