# Generated by Django 3.2.23 on 2024-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountholder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='email',
            field=models.EmailField(help_text="User's Email", max_length=254, unique=True),
        ),
    ]
