# Generated by Django 3.2.23 on 2024-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contract_project'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='su_bcontrator',
            field=models.ManyToManyField(related_name='projects', to='contacts.Subcontractor'),
        ),
    ]
