# Generated by Django 3.2.23 on 2024-01-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_su_bcontrator_project_sub_contrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sub_contrator',
            new_name='sub_contractor',
        ),
    ]
